config/routes.rb
AppSample::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete 

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  root :to => 'static_pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
	attr_accessible :name, :email, :password, :password_confirmation
    has_secure_password
    before_save :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }

	valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
	                  format: { with: valid_email_regex },
                      uniqueness: { case_sensitive: false }

    validates :password, length: { minimum: 6 }
 
    private
      def create_remember_token
      	self.remember_token = SecureRandom.urlsafe_base64
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user 
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create 
    @user = User.new(params[:user])
  	if @user.save
        sign_in @user
        flash[:success] = "Welcome to the Sample App!"
  		  redirect_to @user
  	else
  	    render 'new'
  	end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def logo
		image_tag("logo.png", alt: "Sample App", class: "round")
    end

	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end	 
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def sign_out
		cookies.delete(:remember_token)
	end

	private
	  def user_from_remember_token
	  	remember_token = cookies[:remember_token]
	  	User.find_by_remember_token(remember_token) unless remember_token.nil?
	  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for user, options = { size: 50 } 
		gravatar_id  = Digest::MD5::hexdigest(user.email)
		size = options[:size]
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end 
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
        <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <% if signed_in? %>
              <li> <%= link_to "Profile", current_user %> </li>	
            <% end %>
            <li><%= link_to "Help", help_path %></li>
            <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
        </nav>
</header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', media: 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  media: 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/stylesheets' %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "flash #{key}") %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
  	<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Sample App</h1>
<p>
This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to "Sign up now!", signup_path, class: "signup_button round" %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br/>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
  	<%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<table class="profile">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>